# Generated by Django 5.0.1 on 2024-01-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_global', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Student'), (1, 'Rodic'), (2, 'Ucitel'), (3, 'Vedeni'), (4, 'Ostatni')], default=0),
        ),
    ]
